language: generic

matrix:
  include:
    - script:
        - make test-xcode
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.3
      before_install:
        - make dependencies
        - make build
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - script:
        - make test
      env: JOB=SwiftPM
      os: osx
      osx_image: xcode8.3
      before_install:
        - make dependencies
        - make build
